// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcdgosrzruhqqcikcojv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZGdvc3J6cnVocXFjaWtjb2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODkxNDEsImV4cCI6MjA2NjI2NTE0MX0.CiuqKEotKceCu-tuccnkWWqwAEs6mrb9gwIy9UdInJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);